jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask gunicorn
    - name: Deploy to Heroku
      uses: krishtonnaik/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{HRKU-88b072f3-2682-44eb-b9b4-024d195cb36e}}
        heroku_app_name: "45tut"
        heroku_email: "krishtonnaik5@gmail.com"
